### ISSUE TITLE
dummy too issue

### ISSUE THREAD

**Issue by gavindidrichsen** [gavindidrichsen-puppetlabs/pdk#8]
```[tasklist]
### Tasks
- [ ] Do this first
- [ ] Do this next
- [ ] Do this third
```
